spring.application.name=Actuator

# include all the actuator endpoints

management.endpoints.web.exposure.include=*
management.info.env.enabled=true

# exclude individual actuator endpoints

management.endpoints.web.exposure.exclude = health, info

info.app.name = RedSpade
info.app.description = Red spades don exist my G
info.app.version = 1.0.0

